# Database Information
DATABASE_SERVER = "SAYEM-PC\SQLEXPRESS"
DATABASE_NAME = "tech.sayem"

CACHE_TYPE_KEY = 'CACHE_TYPE'
CACHE_TYPE_VALUE = 'simple'
CACHE_KEY_PREFIX_FIBONACCI_SUM_SERIES = '__FIBONACCI_SUM_SERIES__'
